### ISSUE TITLE
"npm start" fails on windows

### ISSUE THREAD

**Issue by koppor** [cujojs/seed#2]
I'm trying to use `npm start` on windows (at the master branch), but it fails:

``` text
> cujo-quickstart@0.1.0 start C:\git-repositories\linda\linda-frontend
> serv


C:\git-repositories\linda\linda-frontend\node_modules\serv\node_modules\express\node_modules\connect\lib\middleware\static.js:54
  if (!root) throw new Error('static() root path required');
                   ^
Error: static() root path required
    at Object.static (C:\git-repositories\linda\linda-frontend\node_modules\serv\node_modules\express\node_modules\connect\lib\middleware\static.js:54:20)
    at HTTPServer.<anonymous> (C:\git-repositories\linda\linda-frontend\node_modules\serv\bin\serv.js:15:27)
    at HTTPServer.app.configure (C:\git-repositories\linda\linda-frontend\node_modules\serv\node_modules\express\lib\http.js:542:61)
    at Object.<anonymous> (C:\git-repositories\linda\linda-frontend\node_modules\serv\bin\serv.js:14:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! cujo-quickstart@0.1.0 start: `serv`
npm ERR! `cmd "/c" "serv"` failed with 1
npm ERR!
npm ERR! Failed at the cujo-quickstart@0.1.0 start script.
npm ERR! This is most likely a problem with the cujo-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     serv
npm ERR! You can get their info via:
npm ERR!     npm owner ls cujo-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\node\\bin\\\\node.exe" "c:\\node\\bin\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\git-repositories\linda\linda-frontend
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.4
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\git-repositories\linda\linda-frontend\npm-debug.log
npm ERR! not ok code 0
```

npm 1.2.4
and
node v0.8.18

**Comment by briancavalier** [comment]
Pinging @scothis to see if he knows of any problems with serv or express in windows that might be causing this.

**Comment by scothis** [comment]
I've never tried on Windows, I'll take a deeper look

**Comment by briancavalier** [comment]
Thanks!

**Comment by scothis** [comment]
Should be fixed now, run `npm install` again to fetch the latest version of serv.

**Comment by briancavalier** [comment]
@koppor Please give this a go with the latest serv release and let us know if it works for you.

**Comment by koppor** [comment]
Works like a charm. Thank you.

**Comment by briancavalier** [comment]
Great, and big thanks to @scothis for the fast fix :)
